server:
  port: 8008
  servlet:
    context-path: /collateral

spring:
  application:
    name: Collateral
  datasource:
    url: jdbc:postgresql://172.17.90.10:5000/tester
    username: tester
    password: tester1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false